### ISSUE TITLE
Warning: error while hopping to channel xx: iw: out= err=exit status 234

### ISSUE THREAD

**Issue by joao-d-oliveira** [bettercap/bettercap#881]
Got the driver working for [RTL88xBU](https://github.com/cilynx/rtl88x2bu) to set Monitor mode and run bettercap.
Manage to get it running and discovering wifi, but getting bellow consistent errors:
> [19:54:37] [wifi.ap.new] wifi access point xxxx (-86 dBm) detected as xxxx (xxxx).
> [19:54:45] [sys.log] [war] wifi error while hopping to channel 144: iw: out= err=exit status 234
> [19:54:48] [sys.log] [war] wifi error while hopping to channel 169: iw: out= err=exit status 234
> [19:54:49] [sys.log] [war] wifi error while hopping to channel 173: iw: out= err=exit status 234
> [19:54:49] [sys.log] [war] wifi error while hopping to channel 0: iw: out= err=exit status 234
> [19:55:11] [sys.log] [war] wifi error while hopping to channel 0: iw: out= err=exit status 234
> [19:55:23] [wifi.ap.lost] wifi access point xxxx (xxxx) lost.

It does discover well the networks and even managed to test my network and get some packages.
Nevertheless am wondering about the impact of this and what might be causing it.

Any ideas?

-------

### Environment
* Bettercap version: bettercap v2.31.0 (built for linux amd64 with go1.16.3)
* OS: 5.8.0-53-generic #60~20.04.1-Ubuntu
* IW version: iw version 5.4
*IP Version: ip utility, iproute2-ss200127

### Steps to Reproduce
```
sudo ip link set  wlanUSB down
sudo iw dev wlanUSB set type monitor
sudo ip link set wlanUSB up
sudo ./bettercap -iface wlanUSB
wifi.recon on
wifi.show
```

Thanks

**Comment by LZ2DMV** [comment]
Can confirm this. The chipset of my device is RTL8188EU. In my case, the error is:

`[sys.log] [war] wifi error while hopping to channel 14: iw: out=command failed: Invalid argument (-22) err=exit status 234`

Also, when starting:

`[sys.log] [war] wifi error while activating handle: Error: wlx28ee5217c3a5: SIOCGIWPRIV: Argument list too long, interface might already be monitoring. retrying!`

**Comment by ondrejmo** [comment]
> Can confirm this. The chipset of my device is RTL8188EU and i'm using [this](https://github.com/aircrack-ng/rtl8188eus) driver to get monitor mode and frame injection. In my case, the error is:
> 
> `[sys.log] [war] wifi error while hopping to channel 14: iw: out=command failed: Invalid argument (-22) err=exit status 234`
> 
> Also, when starting:
> 
> `[sys.log] [war] wifi error while activating handle: Error: wlx28ee5217c3a5: SIOCGIWPRIV: Argument list too long, interface might already be monitoring. retrying!`

It seems to me that the issue isn't related to a particular chipset, rather it was introduced in some of the last releases (I had the same error message while using TpLink TL-WN722N (AR9271), it didn't have any apparent influence on functionality, but it was kind of annoying). After rollback to version `2.30.1` the error message disappeared from the log.

The interesting part was that it appeared regardless of what channels were selected by `wifi.recon.channel` option.

```
set wifi.interface wlan1
set wifi.region CZ
set wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13

wifi.recon on
```

**Comment by LZ2DMV** [comment]
Well, there is no such message or any other problem with the latest bettercap version on my Intel Corporation PRO/Wireless 5100 AGN PCI-E adapter.

By the way, the adapter i am testing with is also TP-Link WN-722N, but v. 3, with the RTL8188EU chipset. I guess you are using the native Atheros driver in the kernel with your v. 1 adapter, so this is probably not related to the driver indeed, but a bettercap issue itself.

**Comment by evilsocket** [comment]
this should be fixed with the latest version

**Comment by joao-d-oliveira** [comment]
Tkx for the reply @evilsocket .
I just tried with precompiled version:
> "bettercap v2.31.1 (built for linux amd64 with go1.16.4)"

It still gives an error/warning, though now slightly different:
>  error while hopping to channel 0: iw: out=kernel reports: Channel is disabled\ncommand failed: Invalid argument (-22) err=exit status 234"

Is this the version which should be working? Or you mean to compile the source?

**Comment by evilsocket** [comment]
that one .. oh ok so it's not fixed at all ... great XD

**Comment by adamsj182** [comment]
Same problem here but with 3 different adapters (MT7612U, AR9271, & WUSB600N [RT2870]) that all worked just fine a few weeks or months ago. What's odd is that its failing to hop on channels it shouldn't be hopping on to begin with like 0, 169, and 173 which are not used in the US.

Coincidentally (or not coincidence at all), this started happening around the same time Arnaud Rebillout and Re4son imported the firmware-nonfree version 20210315-2+kali1 package with a bunch of changes.

Ref. —> https://pkg.kali.org/news/448823/firmware-nonfree-20210315-2kali1-migrated-to-kali-experimental/

Which bugs the shit out of me because it seems like Re4son is always the last person to mess with everything that keeps breaking and when I roll back whatever it is to before he touched it then everything is back to normal. Those dopes need to put him in the cafeteria dish room where there's no computers. Just sayin…

**Comment by Decapitater** [comment]
any updates @evilsocket  or anyone as the problem persists for arml

**Comment by deanfourie1** [comment]
This is still not resolved for me.

Am using latest version of buttercup, I am getting multiple

Error hopping to channel 12: iw: out=kernal reports: Channel is disabled
Error hopping to channel 13: iw: out=kernal reports: Channel is disabled
Error hopping to channel 14: iw: out=kernal reports: Channel is disabled

I have run a airodump-ng and can confirm that I can see the interface hopping channels fine, but just will not work in bettercap.

Kernal: 5.10.0-kali9-amd64
RTL8188EUS
Using driver 8188EU

Any ideas?

Cheers

**Comment by deanfourie1** [comment]
Bump, can anyone assist with this. Seems to be an issue and is preventing me from progressing.

Thanks

**Comment by joao-d-oliveira** [comment]
I've updated to latest version... `bettercap v2.32.0 (built for linux amd64 with go1.13.8)`, and still face the problem...

My GO coding skills are a bit rusty, but if you want @evilsocket I can give it a try to fix the issue.
To me this looks more like a reporting issue rather than performance, given that it still discovers networks despite the errors. But glad to help further if needed.

**Comment by mordredp** [comment]
it's not an issue with bettercap, it's an issue with some wifi drivers not honoring the regulatory domain

**Comment by adamsj182** [comment]
I actually tried to fix this in two ways:

1.) change wifi adapter settings to regulatory domain which includes the channels Bettercap wants to hop on by default. I found AZ to be a suitable match. Then updated the Linux kernel accordingly.
2.) add the channels Bettercap is trying to hop on to the list of channels to skip.

The second solution worked and was probably where I should have started but at the time it seemed to simple to be true. 

The problem now is that none of these settings persist between runs. I can't find where the conf files are located and I've concluded they're embedded somewhere in a bunch of go code that I know nothing about. Settings for modules using conf-type files persist....just none of the settings to the core features which lack similar configuration files (or I can't find them in the usual places like ../etc/* or ~/.config/*) persist between reboots.

Re-entering the settings every time I run Bettercap has become such a pain that I've all but given up on using it for anything purposeful. This makes me very sad because I think this software is one of the best that I have in my arsenal and I would even be willing to invest $$$ donations for the cause. When these issues are fixed then I'll reconsider.

Thanks and I hope this helps,
JA

**Comment by evilsocket** [comment]
@adamsj182 

> The problem now is that none of these settings persist between runs. I can't find where the conf files are located and I've concluded they're embedded somewhere in a bunch of go code

Configuration and commands can be persisted using caplets. You can find a few examples [here](https://github.com/bettercap/caplets) and more info [here](https://www.bettercap.org/modules/core/caplets/). You can put whatever command you want and load them instead of typing them manually. Like someone else suggested you can just create a .cap file with:

```set wifi.interface wlan1
set wifi.region CZ
set wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13

wifi.recon on
```

> Re-entering the settings every time I run Bettercap has become such a pain that I've all but given up on using it for anything purposeful. 

What if you used that time to read the docs instead? :D 🤯

**Comment by slavadba** [comment]
iw reg get
global
country RU: DFS-UNSET
        (2400 - 2483 @ 40), (N/A, 20), (N/A)
        (5150 - 5350 @ 160), (N/A, 20), (N/A), NO-OUTDOOR
        (5650 - 5850 @ 160), (N/A, 20), (N/A), NO-OUTDOOR
        (57000 - 66000 @ 2160), (N/A, 40), (N/A), NO-OUTDOOR

phy#0
country 99: DFS-UNSET
        (2402 - 2472 @ 40), (N/A, 20), (N/A)
        (2457 - 2482 @ 40), (N/A, 20), (N/A), PASSIVE-SCAN
        (5140 - 5360 @ 80), (N/A, 30), (N/A)
        (5460 - 5860 @ 80), (N/A, 30), (N/A)

                                                                                                                                                            
┌──(root💀kali)-[~]
└─# iwlist wlan0 frequency
wlan0     13 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Current Frequency:2.412 GHz (Channel 1)

                                                                                                                                                            
┌──(root💀kali)-[~]
└─# 

192.168.1.0/24 > 192.168.1.103  » set wifi.region RU
192.168.1.0/24 > 192.168.1.103  » set wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13
192.168.1.0/24 > 192.168.1.103  » wifi.recon on
[16:29:31] [sys.log] [inf] wifi using interface wlan0 (MAC_ADDR)
[16:29:31] [sys.log] [war] wifi could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported
[16:29:31] [sys.log] [war] wifi error while activating handle: error while setting interface wlan0 in monitor mode: Cannot set rfmon for this handle, interface might already be monitoring. retrying!
[16:29:31] [sys.log] [inf] wifi started (min rssi: -200 dBm)
192.168.1.0/24 > 192.168.1.103  » [16:29:31] [sys.log] [inf] wifi channel hopper started.
192.168.1.0/24 > 192.168.1.103  » [16:29:34] [sys.log] [war] wifi error while hopping to channel 14: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
192.168.1.0/24 > 192.168.1.103  » [16:29:38] [sys.log] [war] wifi error while hopping to channel 14: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234

So - this commands don't solve problem .
Or I miss something?

**Comment by evilsocket** [comment]
i'll investigate this further and let you know ... would you be able to provide logs in debug mode (append -debug to the command line)? thanks

**Comment by joao-d-oliveira** [comment]
Ok sending bellow debug... let me know if I can help with anything else.

```
[19:52:00] [sys.log] [inf] wifi using interface wlanUSB (1c:bf:ce:c0:80:01)
[19:52:00] [sys.log] [dbg] SetInterfaceTxPower(wlanUSB, 30) iw based
[19:52:00] [sys.log] [dbg] wifi interface wlanUSB txpower set to 30
[19:52:00] [sys.log] [dbg] creating capture for 'wlanUSB' with options: {Monitor:true Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:500ms}
[19:52:00] [sys.log] [war] wifi error while activating handle: Error: wlanUSB: SIOCGIWPRIV: Argument list too long, interface might already be monitoring. retrying!
[19:52:00] [sys.log] [dbg] creating capture for 'wlanUSB' with options: {Monitor:false Snaplen:65536 Bufsize:2097152 Promisc:true Timeout:500ms}
[19:52:00] [sys.log] [dbg] wifi new frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484 5180 5200 5220 5240 5260 5280 5300 5320 5500 5520 5540 5560 5580 5600 5620 5640 5660 5680 5700 5720 5745 5765 5785 5805 5825 5845 5865 5885]
[19:52:00] [sys.log] [dbg] wifi wifi supported frequencies: [2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484 5180 5200 5220 5240 5260 5280 5300 5320 5500 5520 5540 5560 5580 5600 5620 5640 5660 5680 5700 5720 5745 5765 5785 5805 5825 5845 5865 5885]
[19:52:00] [sys.log] [inf] wifi started (min rssi: -200 dBm)
[19:52:00] [mod.started] wifi
 wlanUSB  » [19:52:00] [sys.log] [dbg] wifi wifi stations pruner started (ap.ttl:5m0s sta.ttl:5m0s).
 wlanUSB  » [19:52:00] [sys.log] [inf] wifi channel hopper started.
 wlanUSB  » [19:52:07] [sys.log] [war] wifi error while hopping to channel 14: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
 wlanUSB  » [19:52:17] [sys.log] [war] wifi error while hopping to channel 144: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
 wlanUSB  » [19:52:20] [sys.log] [war] wifi error while hopping to channel 169: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
 wlanUSB  » [19:52:21] [sys.log] [war] wifi error while hopping to channel 173: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
 wlanUSB  » [19:52:22] [sys.log] [war] wifi error while hopping to channel 177: iw: out=kernel reports: Channel is disabled
command failed: Invalid argument (-22) err=exit status 234
 wlanUSB  » [19:52:25] [wifi.client.probe] station xx:xx:xx:xx:xx:xx (xxxxxxxxxxxx) is probing for SSID xxxxx (-64 dBm)
```

**Comment by ipaqmaster** [comment]
Regardless of channel issues on an individual basis, would it be feasible to have bettercap _stop_ using a channel after it receives a `Channel is disabled` 234 exit code when trying to constantly change to it when the system won't let that happen?

I ask about such a feature as those warnings will continue to spew out during the entire wifi.recon session clogging up the `sys.log` filter, which contains other useful information during recon (So I would love to not have to mute it). As for my adapter (Intel AX201), it loves to ignore and even reset the regulatory region settings (Which I believe bettercap is polling through iwlist as you mentioned) so this is a constant battle for me every time I try to use the software.

These warnings also make the http/https.ui caplet modules difficult to use as the 'Channel is disabled' log lines waterfall down the side of the webpage blocking the view of some UI components.

I've had few peaks through the code and wanted to see if a catch could be made to handle this, potentially making it an optional `set` option in bettercap.

**Comment by winterwolf32** [comment]
> Got the driver working for [RTL88xBU](https://github.com/cilynx/rtl88x2bu) to set Monitor mode and run bettercap. Manage to get it running and discovering wifi, but getting bellow consistent errors:
> 
> > [19:54:37] [wifi.ap.new] wifi access point xxxx (-86 dBm) detected as xxxx (xxxx).
> > [19:54:45] [sys.log] [war] wifi error while hopping to channel 144: iw: out= err=exit status 234
> > [19:54:48] [sys.log] [war] wifi error while hopping to channel 169: iw: out= err=exit status 234
> > [19:54:49] [sys.log] [war] wifi error while hopping to channel 173: iw: out= err=exit status 234
> > [19:54:49] [sys.log] [war] wifi error while hopping to channel 0: iw: out= err=exit status 234
> > [19:55:11] [sys.log] [war] wifi error while hopping to channel 0: iw: out= err=exit status 234
> > [19:55:23] [wifi.ap.lost] wifi access point xxxx (xxxx) lost.
> 
> It does discover well the networks and even managed to test my network and get some packages. Nevertheless am wondering about the impact of this and what might be causing it.
> 
> Any ideas?
> 
> ### Environment
> * Bettercap version: bettercap v2.31.0 (built for linux amd64 with go1.16.3)
> * OS: 5.8.0-53-generic [readline support on windows cmd.exe is broken #60](https://github.com/bettercap/bettercap/issues/60)~20.04.1-Ubuntu
> * IW version: iw version 5.4
>   *IP Version: ip utility, iproute2-ss200127
> 
> ### Steps to Reproduce
> ```
> sudo ip link set  wlanUSB down
> sudo iw dev wlanUSB set type monitor
> sudo ip link set wlanUSB up
> sudo ./bettercap -iface wlanUSB
> wifi.recon on

> wifi.show
> ```
> 
> Thanks

@joao-d-oliveira  Thanks For the solution.
The below steps worked for me. 

> sudo ip link set  wlanUSB down
> sudo iw dev wlanUSB set type monitor
> sudo ip link set wlanUSB up
> sudo ./bettercap -iface wlanUSB
> wifi.recon on

At first, I tried the below because channel no14 is not allowed in all countries. I tried with JP not worked 

set wifi.region CZ
set wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13
wifi.recon on

**Comment by k3ssdev** [comment]
I'm using this one and it's working fine, no more "wifi error while hopping" messages:

 sudo bettercap -eval "events.stream off;set events.stream.output /var/log/bettercap/bettercap.log; events.stream on; set wifi.interface wlan1; set wifi.region ES;wifi.recon.channel 1,2,3,4,5,6,7,8,9,10,11,12,13,36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128,132,136,140;wifi.recon on;https-ui;"

**Comment by yogo1212** [comment]
is there any reason for not using netlink directly?
`iw` explicitly asks not be screenscraped.

`NL80211_BAND_ATTR_FREQS` in `NL80211_ATTR_WIPHY_BANDS` (`NL80211_CMD_GET_WIPHY`) can be used to learn about a devices capabilities.
`NL80211_CMD_GET_REG` can by used with `NL80211_ATTR_WIPHY` as well to get the list of frequencies in the current regulatory domain for a specific phy.

the code should turn out simpler and maybe dropping the dependencies on iw/iwlist is interesting for other reasons as well.

**Comment by renewedbullet** [comment]
any update on a fix for this?

**Comment by evilsocket** [comment]
this has been fixed
