### ISSUE TITLE
Missing License [go-gpsd]

### ISSUE THREAD

**Issue by fvcr** [bettercap/bettercap#938]
Hello,
First of all, thanks for the work with bettercap!

I'm trying to package bettercap for Debian, with that came the need to package bettercap dependencies, the same ones I find in [go.mod](https://github.com/bettercap/bettercap/blob/ed4239fad52888bfb00939c304d1ff34990e0537/go.mod).

There is one dependency [github.com/koppacetic/go-gpsd](https://github.com/bettercap/bettercap/blob/ed4239fad52888bfb00939c304d1ff34990e0537/go.mod#L33) that is missing the license, this is an obstacle for me to proceed with packaging.

Since this library is a [fork](https://github.com/koppacetic/go-gpsd), I tried to contact the upstream of [go-gpsd](https://github.com/stratoberry/go-gpsd) by email and got no response, there is an open [issue](https://github.com/stratoberry/go-gpsd/issues/5) for this since 2017.

From what I have seen, the module that uses this library is the [module/gps/gps.go:go-gpsd](https://github.com/bettercap/bettercap/blob/ed4239fad52888bfb00939c304d1ff34990e0537/modules/gps/gps.go)

I would be very grateful if @bettercap could help with this, any suggestions?

Thanks a lot!

**Comment by josip** [comment]
Hi there, I'm the author of the original library at stratoberry/go-gpsd - I've added the MIT License to the original repository so I think you may be able to close this issue now.

I have also merged changes that were present in koppacetic/go-gpsd branch into the main repository and tagged it as v1.0.0.

Thank you for your patience and love seeing the library being used in your project! 🔒

**Comment by evilsocket** [comment]
thanks guys

**Comment by samueloph** [comment]
Can this issue be reopened @evilsocket?

Bettercap is still using the unlicensed go-gspd, as seen in the go.mod file:
https://github.com/bettercap/bettercap/blob/e224eea8c62906406f8560a576782d598908782c/go.mod#L33

I thought it would be possible to switch to upstream's go-gpsd from @josip but I can see a small delta between that repo and the one under koppacetic, you might be interested in checking the diff as there might be something you would like to use, josip@.

evilsocket@, If you're fine with using upstream's (josip@) go-gpsd, then that solves the issue, otherwise the fork (koppacetic) will also have to update its license, for both alternatives the go.mod file will have to be updated to point to the correct release.

**Comment by samueloph** [comment]
Ping, just in case you missed this by accident @evilsocket @josip

**Comment by evilsocket** [comment]
@samueloph done, apologies for the long time.

@josip there's no way to stop the reader (and interrupt the watch loop) in this new gpsd, could you add it?
